apiVersion: v2
name: attack-simulation
description: A Job Helm chart for Kubernetes to simulate MITRE ATT&CK techniques
type: application
version: 1.2.0
appVersion: latest
keywords:
  - job
  - security
  - mitre
  - attack-simulation
maintainers:
  - name: aliaksxssv
icon: https://cdn-icons-png.flaticon.com/512/6150/6150615.png
